openapi: 3.0.3
info:
  title: PowerLink API
  version: 1.0.0
  description: |
    # PowerLink API
    
    ## Introduction
    The PowerLink3 module provides a JSON-RPC interface for interacting with Visonic/Tyco alarm panels. 
    This interface allows for various operations.
    
    Parameter order does matter so make sure to check the order of the parameters in the parameters section
    
    ## Authentication
    For some methods, the client needs to be registered first, see the `Register Client` method.
servers:
    - url: http://<MODULE IP>:8181/remote/json-rpc
      description: PowerLink API

security: []
tags: []
paths: []
